POST http://localhost:5001/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsImVtYWlsIjoidG9kMUBnbWFpbC5jb20iLCJpYXQiOjE3NzE4MjQwMDYsImV4cCI6MTc3MTgyNzYwNiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3QifQ.t7ViEAiCH3auy7iwt1b03lpNPbMfcNeVPjw1OnqXKiY

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsImlhdCI6MTc3MTgyNDAwNiwiZXhwIjoxNzcxOTEwNDA2LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdCJ9.t9h9Pck6dgUJjF2W9bsgkA1W7reOXYbcZBwGfTgCMW0"
}