GET http://localhost:5001/project/get-all?page=1&limit=100
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJlbWFpbCI6ImFkbWluQHRhc2tmb3JnZS5jb20iLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3NzQxOTM1NDcsImV4cCI6MTc3NDE5NzE0NywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3QifQ.ixPolgCoUXkixwpYC4woAbC3454_8v4voI2VL3C3MPA