GET http://localhost:5001/project/get-all?page=1&limit=100
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJlbWFpbCI6ImFkbWluQHRhc2tmb3JnZS5jb20iLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3NzQwMjI5MDUsImV4cCI6MTc3NDAyNjUwNSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3QifQ.svXFSRmXjbKi33sjAFav6SDGudPKR1_fGaHP5DBCyLE
